from app.models.rol import Rol
from app.models.permiso import Permiso
from app.models.usuario import Usuario
from app.models.producto import Producto
from app.models.servicio import Servicio
from app.models.pedido import Pedido
from app.models.detalle_pedido import DetallePedido
from app.models.venta import Venta
from app.models.detalle_venta import DetalleVenta
from app.models.factura import Factura
from app.models.detalle_factura import DetalleFactura
from app.models.pqr import PQR
from app.models.conversacion import Conversacion
from app.models.mensaje import Mensaje
